### ISSUE TITLE
Error: Cannot find module '@tensorflow/tfjs-node

### ISSUE THREAD

**Issue by guillad** [dceejay/tfjs-nodes#1]
Hi, Thnaks for this great node.
However, when trying to run this simple example flow:

`[{"id":"2ef76e65.62f3b2","type":"tensorflowCoco","z":"d387832.4d4888","name":"","model":"","x":870,"y":180,"wires":[["52cb519.af570b","1ad38862.f5ba58"]]},{"id":"52cb519.af570b","type":"debug","z":"d387832.4d4888","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","targetType":"msg","x":1170,"y":220,"wires":[]},{"id":"1ad38862.f5ba58","type":"debug","z":"d387832.4d4888","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"classes","targetType":"msg","x":1170,"y":260,"wires":[]},{"id":"23fd6478.e0b08c","type":"http request","z":"d387832.4d4888","name":"","method":"GET","ret":"bin","paytoqs":false,"url":"https://loremflickr.com/320/240/sport","tls":"","persist":false,"proxy":"","authType":"","x":690,"y":120,"wires":[["2ef76e65.62f3b2"]]},{"id":"8a8a2d67.bf319","type":"inject","z":"d387832.4d4888","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":500,"y":160,"wires":[["23fd6478.e0b08c"]]}]`

I get the following error: "Error: Cannot find module '@tensorflow/tfjs-node"

![image](https://user-images.githubusercontent.com/57844677/73548288-2c9cdb00-4449-11ea-918b-a30325385c05.png)

Thanks again :-)

**Comment by dceejay** [comment]
closed by 6d55028de20eebdb6a37c686ac175df9c9042998
